[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "cd d5news-react && npm install"]

[phases.build]
cmds = ["cd d5news-react && npm run build"]

[start]
cmd = "node server.js"
